import type { LeaguePlayer, Match, League } from "@/types"

export const mockLeague: League = {
  id: "mock-league-1",
  name: "Summer 2025",
  slug: "summer-2025",
  divisions: ["Leonardo", "Donatello", "Michelangelo", "Raphael"],
  isActive: true,
  startDate: "2025-06-01",
  endDate: "2025-08-31",
}

export const mockPlayers: LeaguePlayer[] = [
  { id: "1", playerId: "p1", leagueId: "mock-league-1", playerName: "John Smith", division: "Leonardo", rating: "4.0" },
  { id: "2", playerId: "p2", leagueId: "mock-league-1", playerName: "Sarah Johnson", division: "Leonardo", rating: "3.5" },
  { id: "3", playerId: "p3", leagueId: "mock-league-1", playerName: "Mike Davis", division: "Donatello", rating: "4.0" },
  { id: "4", playerId: "p4", leagueId: "mock-league-1", playerName: "Emily Wilson", division: "Donatello", rating: "3.5" },
  { id: "5", playerId: "p5", leagueId: "mock-league-1", playerName: "Chris Brown", division: "Michelangelo", rating: "4.5" },
  { id: "6", playerId: "p6", leagueId: "mock-league-1", playerName: "Lisa Garcia", division: "Michelangelo", rating: "4.0" },
  { id: "7", playerId: "p7", leagueId: "mock-league-1", playerName: "David Miller", division: "Raphael", rating: "3.0" },
  { id: "8", playerId: "p8", leagueId: "mock-league-1", playerName: "Anna Taylor", division: "Raphael", rating: "3.5" },
]

export const mockMatches: Match[] = [
  {
    id: "1",
    player1Id: "1",
    player2Id: "2",
    player1Sets: 2,
    player2Sets: 1,
    player1Games: 13,
    player2Games: 7,
    setsDetail: [
      { player1Games: 6, player2Games: 4, setWinnerId: "1" },
      { player1Games: 3, player2Games: 6, setWinnerId: "2" },
      { player1Games: 10, player2Games: 8, setWinnerId: "1" },
    ],
    winnerId: "1",
    date: "2024-01-15",
    score: "6-4, 3-6, 10-8",
    leagueId: "mock-league-1",
  },
  {
    id: "2",
    player1Id: "3",
    player2Id: "4",
    player1Sets: 1,
    player2Sets: 2,
    player1Games: 10,
    player2Games: 12,
    setsDetail: [
      { player1Games: 3, player2Games: 6, setWinnerId: "4" },
      { player1Games: 6, player2Games: 2, setWinnerId: "3" },
      { player1Games: 8, player2Games: 10, setWinnerId: "4" },
    ],
    winnerId: "4",
    date: "2024-01-16",
    score: "6-3, 2-6, 10-8",
    leagueId: "mock-league-1",
  },
  {
    id: "3",
    player1Id: "5",
    player2Id: "6",
    player1Sets: 2,
    player2Sets: 0,
    player1Games: 12,
    player2Games: 4,
    setsDetail: [
      { player1Games: 6, player2Games: 2, setWinnerId: "5" },
      { player1Games: 6, player2Games: 2, setWinnerId: "5" },
    ],
    winnerId: "5",
    date: "2024-01-17",
    leagueId: "mock-league-1",
  },
  {
    id: "4",
    player1Id: "7",
    player2Id: "8",
    player1Sets: 1,
    player2Sets: 2,
    player1Games: 11,
    player2Games: 12,
    setsDetail: [
      { player1Games: 4, player2Games: 6, setWinnerId: "8" },
      { player1Games: 6, player2Games: 4, setWinnerId: "7" },
      { player1Games: 10, player2Games: 12, setWinnerId: "8" },
    ],
    winnerId: "8",
    date: "2024-01-18",
    leagueId: "mock-league-1",
  },
  {
    id: "5",
    player1Id: "1",
    player2Id: "3",
    player1Sets: 2,
    player2Sets: 0,
    player1Games: 12,
    player2Games: 6,
    setsDetail: [
      { player1Games: 6, player2Games: 3, setWinnerId: "1" },
      { player1Games: 6, player2Games: 3, setWinnerId: "1" },
    ],
    winnerId: "1",
    date: "2024-01-19",
    leagueId: "mock-league-1",
  },
]
